-- MySQL Script generated by MySQL Workbench
-- 03/31/16 12:03:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crf` DEFAULT CHARACTER SET utf8 ;
USE `crf` ;
-- -----------------------------------------------------
-- Table `crf`.`secuencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`secuencias` (
  `id_secuencia` INT NOT NULL,
  `clave` VARCHAR(5) NULL,
  `carrera` VARCHAR(45) NULL,
  PRIMARY KEY (`id_secuencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`edificios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`edificios` (
  `id_edificio` INT NOT NULL,
  `clave` VARCHAR(2) NULL,
  PRIMARY KEY (`id_edificio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`academias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`academias` (
  `id_academia` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `id_edificio` INT NOT NULL,
  PRIMARY KEY (`id_academia`, `id_edificio`),
  INDEX `fk_id_edificio_idx` (`id_edificio` ASC),
  CONSTRAINT `fk_id_edificio`
    FOREIGN KEY (`id_edificio`)
    REFERENCES `crf`.`edificios` (`id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`materias` (
  `id_materia` INT NOT NULL,
  `clave` VARCHAR(10) NULL,
  `nombre` VARCHAR(100) NULL,
  `id_secuencia` INT NOT NULL,
  `id_academia` INT NOT NULL,
  PRIMARY KEY (`id_materia`, `id_secuencia`, `id_academia`),
  INDEX `fk_materias_secuencias1_idx` (`id_secuencia` ASC),
  INDEX `fk_materias_academias1_idx` (`id_academia` ASC),
  CONSTRAINT `fk_materias_secuencias1`
    FOREIGN KEY (`id_secuencia`)
    REFERENCES `crf`.`secuencias` (`id_secuencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materias_academias1`
    FOREIGN KEY (`id_academia`)
    REFERENCES `crf`.`academias` (`id_academia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`salones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`salones` (
  `id_salon` INT NOT NULL,
  `clave` VARCHAR(10) NULL,
  `id_edificio` INT NULL,
  PRIMARY KEY (`id_salon`, `id_edificio`),
  INDEX `fk_id_edificio1_idx` (`id_edificio` ASC),
  CONSTRAINT `fk_id_edificio1`
    FOREIGN KEY (`id_edificio`)
    REFERENCES `crf`.`edificios` (`id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`dias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`dias` (
  `id_dia` INT NOT NULL,
  `clave` VARCHAR(1) NULL,
  `nombre` VARCHAR(9) NULL,
  PRIMARY KEY (`id_dia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crf`.`materias_salones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crf`.`materias_salones` (
  `id_materias_salones` INT NOT NULL,
  `id_materia` INT NOT NULL,
  `id_salon` INT NOT NULL,
  `id_dia` INT NOT NULL,
  PRIMARY KEY (`id_materias_salones`, `id_materia`, `id_salon`, `id_dia`),
  INDEX `fk_materias_salones_materias1_idx` (`id_materia` ASC),
  INDEX `fk_materias_salones_salones1_idx` (`id_salon` ASC),
  INDEX `fk_materias_salones_dias1_idx` (`id_dia` ASC),
  CONSTRAINT `fk_materias_salones_materias1`
    FOREIGN KEY (`id_materia`)
    REFERENCES `crf`.`materias` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materias_salones_salones1`
    FOREIGN KEY (`id_salon`)
    REFERENCES `crf`.`salones` (`id_salon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materias_salones_dias1`
    FOREIGN KEY (`id_dia`)
    REFERENCES `crf`.`dias` (`id_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
